theme = "docuapi"
themesdir = "./themes"
languageCode = "en-us"
baseurl = "https://docuapi.netlify.com/"
title = "QRL API Docs"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "javascript"
name = "Javascript"
#[[params.language_tabs]]
#key = "go"
#name = "Go" 
[[params.language_tabs]]
key = "shell"
name = "Shell" 
#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
[[params.language_tabs]]
key = "python"
name = "Python"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]

[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.nn]
languageName = "Nynorsk"
weight = 1
title = "DocuAPI-døme"

